name: Test
on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: g#KoK0iYxF&525VJ65rG
          POSTGRES_USER: pecora
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      - name: Cache
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv sync --dev
      - name: Lint with Flake8
        run: pipenv run flake8
      - name: isort
        run: pipenv run isort . -c
      - name: Test with pytest
        run: pipenv run pytest
